<?xml version="1.0" encoding="UTF-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>pwrplatf_RuntimeExtensionCommonPlugins</PackageId>
    <Version>3.0.0</Version>
    <Description>No description provided.</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PowerPlatformTargetSolutionFolder Include="..\..\powerplatform\PowerPlatformRuntimeExtensions" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference
      Include="
        FredrikHr.NupkgMSBuild.PackPackageReference;
        FredrikHr.NupkgMSBuild.PackProjectReference;
        "
      PrivateAssets="all"
    >
      <ProjectReference>$(MSBuildThisFileDirectory)..\..\.submodules\fredrikhr\powerplatform-sdk-extensions\.submodules\fredrikhr\nuget-msbuild-extensions\build\%(Identity)\%(Identity).csproj</ProjectReference>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" PrivateAssets="all" />
    <PackageReference Include="System.IO.Hashing" Pack="true" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\.submodules\fredrikhr\powerplatform-sdk-extensions\libraries\FredrikHr.PowerPlatformSdkExtensions.ApiDiscovery\FredrikHr.PowerPlatformSdkExtensions.ApiDiscovery.csproj">
      <Pack>true</Pack>
    </ProjectReference>
  </ItemGroup>

</Project>
